# Generated by Django 5.2 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(db_index=True)),
                ('client_id', models.IntegerField(db_index=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('card_last4', models.CharField(max_length=4)),
                ('card_expiry', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('APPROVED', 'Aprobado'), ('DECLINED', 'Rechazado')], max_length=20)),
                ('transaction_reference', models.CharField(db_index=True, max_length=40, unique=True)),
                ('response_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
